# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.56.101',
	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 100,
			:port => 1
		},
		:sata2 => {
                        :dfile => './sata2.vdi',
                        :size => 100, # Megabytes
			:port => 2
		},
                :sata3 => {
                        :dfile => './sata3.vdi',
                        :size => 100,
                        :port => 3
                },
                :sata4 => {
                        :dfile => './sata4.vdi',
                        :size => 100, # Megabytes
                        :port => 4
                },
                :sata5 => {
                        :dfile => './sata5.vdi',
                        :size => 100, # Megabytes
                        :port => 5
                }

	}
        
        
		
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
              sudo sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
              sudo sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
              sudo sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
              sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
              sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
              sudo yum clean all
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	      yum install -y mdadm smartmontools hdparm gdisk
        #       sudo mdadm --zero-superblock --force /dev/sd{b,c,d,e}
        #       yes | sudo mdadm --create --verbose /dev/md0 -l 1 -n 2 /dev/sd{b,d}
        #       yes | sudo mdadm --create --verbose /dev/md1 -l 1 -n 2 /dev/sd{c,e}
        #       yes | sudo mdadm --create --verbose /dev/md10 -l 0 -n 2 /dev/md0 /dev/md1
        #       sudo mkdir /etc/mdadm
        #       sudo touch /etc/mdadm/mdadm.conf
        #       sudo mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> /etc/mdadm/mdadm.conf
        #       sudo parted -s /dev/md10 mklabel gpt
        #       yes | sudo parted /dev/md10 mkpart primary ext4 0% 20%
        #       yes | sudo parted /dev/md10 mkpart primary ext4 20% 40%
        #       yes | sudo parted /dev/md10 mkpart primary ext4 40% 60%
        #       yes | sudo parted /dev/md10 mkpart primary ext4 60% 80%
        #       yes | sudo parted /dev/md10 mkpart primary ext4 80% 100%
        #       yes | for i in $(seq 1 5); do sudo mkfs.ext4 /dev/md10p$i; done
        #       sudo mkdir -p /raid/part{1,2,3,4,5}
        #       sudo mount /dev/md10p1 /raid/part1
        #       sudo mount /dev/md10p2 /raid/part2
        #       sudo mount /dev/md10p3 /raid/part3
        #       sudo mount /dev/md10p4 /raid/part4
        #       sudo mount /dev/md10p5 /raid/part5
        #       cat /proc/mdstat



  	  SHELL

      end
  end
end

